# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. These parameters are retrieved using config::get() of
# the config R package <https://rstudio.github.io/config/>.
#


default:
  tag_create: # ?tag_create()
    # crop_start: "2024-07-14" # Generally set at the tag level
    # crop_end: NULL
  tag_label: # ? tag_label()
    warning_flight_duration: 2 # hours
    warning_stap_duration: 6 # hours
  tag_set_map: # ?tag_set_map()
    extent: [-100, -75, 2, 36] # [W, E, S, N]
    scale: 5 # 1 (min) -> 1째 ; 2 -> 0.5째 ; 5 -> 0.25째 ; 10 (max) -> 0.1째
    include_stap_id: NULL # default, take all
    include_min_duration: 0 # in hours
  geopressure_map: # ?geopressure_map()
    max_sample: 250
    margin: 20 # in m
    sd: 1
    thr_mask: 0.9
    log_linear_pooling_weight: !expr \(n) log(n)/n
  twilight_create: # ?twilight_create()
    # twl_thr: NULL
    # twl_offset: NULL # in hours
  geolight_map: # ?geolight_map()
    twl_calib_adjust: 1.4
    twl_llp: !expr \(n) log(n)/n
  graph_create: # ?graph_create()
    thr_likelihood: 0.99
    thr_gs: 150 # km/h
    # likelihood: NULL # Best to leave NULL.
  graph_add_wind:
    thr_as: 90 # km/h
  graph_set_movement: # ?graph_set_movement()
    # type: "gs"
    # method: "gamma"
    # shape: 7 # only for gamma
    # scale: 7
    # location: 40 # only for logistic
    # low_speed_fix: 15 # km/h
    # zero_speed_ratio: 1
  graph_simulation: # ?graph_simulation()
    nj: 10
  pressurepath_create: # ?pressurepath_create()
    variable: ["altitude", "surface_pressure"]
    # solar_dep: 0
  geopressuretemplate: # ?geopressuretemplate()
    likelihood: ["map_pressure"]
    outputs: ["marginal", "most_likely", "simulation"]
    pressurepath: ["most_likely"] # "geopressureviz"

CV019:
  tag_create:
    crop_start: "2024-07-14"
    crop_end: "2025-05-22"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -83.36408
      known_lat: 33.89285
  bird_create:
    scientific_name: "Hylocichla mustelina"
  graph_set_movement:
    type: "gs" 


